name: Check

on: [push, pull_request]

jobs:
  ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check formatting
        run: npx prettier --check src
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check formatting
        run: cargo fmt -- --check
        working-directory: src-tauri
      - name: Check program validity
        run: cargo check
        working-directory: src-tauri
